import type { AppPermission, AppRole } from "@web-scada/shared";

export const ALL_PERMISSIONS: AppPermission[] = [
  "runtime.view",
  "runtime.control",
  "editor.view",
  "editor.write",
  "screens.view",
  "screens.write",
  "screens.delete",
  "tags.view",
  "tags.write",
  "tags.delete",
  "tags.import",
  "tags.export",
  "drivers.view",
  "drivers.write",
  "drivers.delete",
  "assets.view",
  "assets.write",
  "assets.delete",
  "libraries.view",
  "libraries.write",
  "libraries.delete",
  "elements.view",
  "elements.write",
  "elements.delete",
  "macros.view",
  "macros.write",
  "macros.delete",
  "macros.run",
  "users.view",
  "users.write",
  "users.delete",
  "users.changePassword",
  "settings.view",
  "settings.write",
];

export const ROLE_PERMISSIONS: Record<AppRole, AppPermission[]> = {
  admin: [...ALL_PERMISSIONS],
  engineer: [
    "runtime.view",
    "runtime.control",
    "editor.view",
    "editor.write",
    "screens.view",
    "screens.write",
    "screens.delete",
    "tags.view",
    "tags.write",
    "tags.delete",
    "tags.import",
    "tags.export",
    "drivers.view",
    "drivers.write",
    "drivers.delete",
    "assets.view",
    "assets.write",
    "assets.delete",
    "libraries.view",
    "libraries.write",
    "libraries.delete",
    "elements.view",
    "elements.write",
    "elements.delete",
    "macros.view",
    "macros.write",
    "macros.delete",
    "macros.run",
    "settings.view",
    "settings.write",
  ],
  operator: [
    "runtime.view",
    "runtime.control",
    "screens.view",
    "tags.view",
    "drivers.view",
    "macros.view",
  ],
  viewer: ["runtime.view", "screens.view", "tags.view"],
};
