import type { HmiObject, TextStyle } from "@web-scada/shared";

const defaultTextStyle: TextStyle = {
  fontFamily: "Arial",
  fontSize: 16,
  color: "#ffffff",
  horizontalAlign: "center",
  verticalAlign: "middle",
  fontStyle: "normal",
  padding: 4,
};

function id(prefix: string): string {
  return `${prefix}_${Math.random().toString(36).slice(2, 8)}`;
}

export function createObjectByType(type: HmiObject["type"]): HmiObject {
  switch (type) {
    case "group":
      return {
        id: id("group"),
        type,
        x: 100,
        y: 100,
        width: 200,
        height: 120,
        minWidth: 20,
        minHeight: 20,
        objects: [],
      };
    case "text":
      return {
        id: id("text"),
        type,
        x: 80,
        y: 80,
        width: 180,
        height: 40,
        minWidth: 60,
        minHeight: 24,
        text: "Text",
        textStyle: { ...defaultTextStyle, horizontalAlign: "left" },
      };
    case "line":
      return {
        id: id("line"),
        type,
        x: 100,
        y: 100,
        width: 140,
        height: 20,
        minWidth: 20,
        minHeight: 10,
        points: [0, 10, 140, 10],
        stroke: "#d9d9d9",
        strokeWidth: 3,
        closed: false,
        activeValue: 1,
        inactiveStroke: "#d9d9d9",
        activeStroke: "#0e639c",
        gradientEnabled: false,
        gradientDirection: "horizontal",
      };
    case "rectangle":
      return {
        id: id("rect"),
        type,
        x: 100,
        y: 100,
        width: 140,
        height: 80,
        minWidth: 30,
        minHeight: 20,
        fill: "#262626",
        stroke: "#8c8c8c",
        gradientEnabled: false,
        gradientDirection: "horizontal",
      };
    case "value-display":
      return {
        id: id("val"),
        type,
        x: 100,
        y: 100,
        width: 180,
        height: 40,
        minWidth: 80,
        minHeight: 28,
        tag: "",
        suffix: " kPa",
        badQualityText: "BAD",
        textStyle: { ...defaultTextStyle, color: "#ffd666", horizontalAlign: "right" },
      };
    case "value-input":
      return {
        id: id("input"),
        type,
        x: 100,
        y: 100,
        width: 170,
        height: 44,
        minWidth: 80,
        minHeight: 28,
        tag: "",
        confirm: true,
        textStyle: { ...defaultTextStyle },
      };
    case "state-indicator":
      return {
        id: id("state"),
        type,
        x: 100,
        y: 100,
        width: 160,
        height: 44,
        minWidth: 80,
        minHeight: 28,
        tag: "",
        trueText: "ON",
        falseText: "OFF",
        trueColor: "#389e0d",
        falseColor: "#595959",
        badColor: "#bfbfbf",
        gradientEnabled: false,
        gradientDirection: "horizontal",
        textStyle: { ...defaultTextStyle },
      };
    case "button":
      return {
        id: id("btn"),
        type,
        x: 100,
        y: 100,
        width: 130,
        height: 44,
        minWidth: 60,
        minHeight: 24,
        text: "Start",
        showText: true,
        backgroundColor: "#0958d9",
        pressedBackgroundColor: "#0747b3",
        disabledBackgroundColor: "#434343",
        borderColor: "#0958d9",
        borderWidth: 1,
        gradientEnabled: false,
        gradientDirection: "horizontal",
        textStyle: { ...defaultTextStyle },
        action: { type: "pulse", tag: "", value: true, durationMs: 500 },
      };
    case "switch":
      return {
        id: id("switch"),
        type,
        x: 100,
        y: 100,
        width: 130,
        height: 44,
        minWidth: 70,
        minHeight: 28,
        tag: "",
        onText: "ON",
        offText: "OFF",
        onColor: "#389e0d",
        offColor: "#434343",
        borderColor: "#595959",
        borderWidth: 1,
        gradientEnabled: false,
        gradientDirection: "horizontal",
        textStyle: { ...defaultTextStyle },
      };
    case "image":
      return {
        id: id("img"),
        type,
        x: 100,
        y: 100,
        width: 140,
        height: 100,
        minWidth: 40,
        minHeight: 40,
        fit: "contain",
        preserveAspectRatio: true,
        opacity: 1,
      };
    case "stateImage":
      return {
        id: id("state_img"),
        type,
        x: 100,
        y: 100,
        width: 140,
        height: 100,
        minWidth: 40,
        minHeight: 40,
        tag: ".State",
        states: [],
        fit: "contain",
        preserveAspectRatio: true,
      };
    case "valueSelect":
      return {
        id: id("value_select"),
        type,
        x: 100,
        y: 100,
        width: 180,
        height: 44,
        minWidth: 90,
        minHeight: 28,
        valueType: "string",
        target: { type: "internal", name: "selectedBurnerPrefix" },
        options: [
          { label: "Burner 1", value: "_1" },
          { label: "Burner 2", value: "_2" },
          { label: "Burner 3", value: "_3" },
        ],
        textStyle: { ...defaultTextStyle },
      };
    case "libraryElementInstance":
      return {
        id: id("lib"),
        type,
        x: 100,
        y: 100,
        width: 180,
        height: 120,
        minWidth: 60,
        minHeight: 40,
        libraryId: "",
        elementId: "",
        bindingAssignments: {},
        scaleMode: "fit",
      };
    case "valve":
      return {
        id: id("valve"),
        type,
        x: 100,
        y: 100,
        width: 120,
        height: 90,
        minWidth: 60,
        minHeight: 50,
        label: "PZK-1",
        openTag: "Valve_1.Opened",
        closedTag: "Valve_1.Closed",
        errorTag: "Valve_1.Fault",
        textStyle: { ...defaultTextStyle, fontSize: 12 },
      };
    case "pump":
      return {
        id: id("pump"),
        type,
        x: 100,
        y: 100,
        width: 130,
        height: 90,
        minWidth: 60,
        minHeight: 50,
        label: "Fan-1",
        runTag: "Fan_1.Run",
        faultTag: "Fan_1.Fault",
        textStyle: { ...defaultTextStyle, fontSize: 12 },
      };
    case "frame":
      return {
        id: id("frame"),
        type,
        x: 100,
        y: 100,
        width: 220,
        height: 120,
        minWidth: 80,
        minHeight: 50,
        screenId: "",
        showBorder: true,
        borderColor: "#888",
        borderWidth: 1,
        scaleMode: "fit",
      };
    case "checkbox":
      return {
        id: id("chk"),
        type,
        x: 100,
        y: 100,
        width: 160,
        height: 32,
        minWidth: 60,
        minHeight: 24,
        label: "Checkbox",
        checkedText: "On",
        uncheckedText: "Off",
        checkedColor: "#0e639c",
        uncheckedColor: "#2d2d2d",
      };
    case "slider":
      return {
        id: id("sldr"),
        type,
        x: 100,
        y: 100,
        width: 220,
        height: 44,
        minWidth: 100,
        minHeight: 32,
        min: 0,
        max: 100,
        step: 1,
        orientation: "horizontal",
        showValue: true,
        fillColor: "#0e639c",
        trackColor: "#2d2d2d",
        thumbColor: "#cccccc",
        backgroundColor: "#1e1e1e",
        borderColor: "#3c3c3c",
        borderWidth: 1,
        cornerRadius: 4,
        trackThickness: 4,
        thumbRadius: 7,
        thumbBorderColor: "#3c3c3c",
        textColor: "#cccccc",
        fontFamily: "Consolas",
        fontSize: 12,
        decimals: 1,
        valuePosition: "bottom",
        showMinMax: false,
        minMaxFontSize: 10,
        minLabelOffset: 2,
        maxLabelOffset: 2,
        writeOnRelease: false,
        dragWriteIntervalMs: 50,
        releaseSyncHoldMs: 2500,
        badColor: "#a03030",
        badTextColor: "#f14c4c",
        disabledColor: "#3d3d3d",
        disabledTextColor: "#8c8c8c",
        transparentBackground: false,
      };
    case "progress-bar":
      return {
        id: id("pgbar"),
        type,
        x: 100,
        y: 100,
        width: 220,
        height: 32,
        minWidth: 80,
        minHeight: 20,
        min: 0,
        max: 100,
        showValue: true,
        fillColor: "#0e639c",
        trackColor: "#2d2d2d",
        backgroundColor: "#1e1e1e",
        borderColor: "#3c3c3c",
        borderWidth: 1,
        cornerRadius: 4,
        padding: 2,
        textColor: "#ffffff",
        fontFamily: "Consolas",
        fontSize: 12,
        decimals: 1,
        showPercent: true,
        showUnit: false,
        fillDirection: "left-to-right",
        warningColor: "#d7ba7d",
        badTextColor: "#f14c4c",
        badBackgroundColor: "#2b1a1a",
        badBorderColor: "#a03030",
        disabledBackgroundColor: "#3d3d3d",
        disabledTextColor: "#8c8c8c",
        alarmColor: "#f14c4c",
      };
    case "select":
      return {
        id: id("sel"),
        type,
        x: 100,
        y: 100,
        width: 180,
        height: 32,
        minWidth: 80,
        minHeight: 24,
        placeholder: "Select...",
        options: [
          { label: "Option 1", value: 1 },
          { label: "Option 2", value: 2 },
        ],
        backgroundColor: "#1e1e1e",
        borderColor: "#3c3c3c",
        borderWidth: 1,
        cornerRadius: 4,
        textColor: "#cccccc",
        placeholderColor: "#8c8c8c",
        fontFamily: "Consolas",
        fontSize: 12,
        padding: 8,
        arrowColor: "#cccccc",
        dropdownBackgroundColor: "#252526",
        dropdownBorderColor: "#3c3c3c",
        optionTextColor: "#cccccc",
        optionHoverColor: "#2d2d2d",
        optionSelectedColor: "rgba(14, 99, 156, 0.3)",
        optionSelectedTextColor: "#ffffff",
        dropdownMaxHeight: 200,
        dropdownOffsetY: 2,
        optionHeight: 28,
        arrowAreaWidth: 24,
        badTextColor: "#f14c4c",
        badBackgroundColor: "#2b1a1a",
        badBorderColor: "#a03030",
        disabledBackgroundColor: "#3d3d3d",
        disabledTextColor: "#8c8c8c",
      };
    case "radio-group":
      return {
        id: id("rgrp"),
        type,
        x: 100,
        y: 100,
        width: 220,
        height: 60,
        minWidth: 100,
        minHeight: 36,
        orientation: "horizontal",
        options: [
          { label: "A", value: "A" },
          { label: "B", value: "B" },
        ],
        backgroundColor: "#1e1e1e",
        borderColor: "#3c3c3c",
        borderWidth: 1,
        cornerRadius: 4,
        itemGap: 2,
        itemPadding: 4,
        radioSize: 12,
        radioStrokeWidth: 1.5,
        indicatorGap: 6,
        itemInset: 4,
        selectedColor: "#0e639c",
        unselectedColor: "#3c3c3c",
        labelColor: "#cccccc",
        selectedLabelColor: "#ffffff",
        fontFamily: "Consolas",
        fontSize: 12,
        gradientEnabled: false,
        gradientDirection: "horizontal",
        styleMode: "radio",
        badTextColor: "#f14c4c",
        badBackgroundColor: "#2b1a1a",
        disabledColor: "#3d3d3d",
        disabledTextColor: "#8c8c8c",
        transparentBackground: true,
      };
    case "numeric-input":
      return {
        id: id("nmin"),
        type,
        x: 100,
        y: 100,
        width: 140,
        height: 32,
        minWidth: 80,
        minHeight: 24,
        min: 0,
        max: 100,
        step: 1,
        decimals: 0,
        formatMode: "decimals",
        showUnit: true,
        placeholder: "0",
        backgroundColor: "#1e1e1e",
        borderColor: "#3c3c3c",
        borderWidth: 1,
        cornerRadius: 4,
        textColor: "#ffffff",
        showMeta: true,
        stepButtonUseTextColor: true,
        stepButtonTextColor: "#cccccc",
        stepButtonBackgroundColor: "#2d2d2d",
        badTextColor: "#f14c4c",
        badBackgroundColor: "#2b1a1a",
        badBorderColor: "#a03030",
        fontSize: 12,
        fontFamily: "Consolas",
        textAlign: "right",
        dialogTitle: "Set Value",
        dialogWidth: 300,
        dialogHeight: 150,
        dialogX: 200,
        dialogY: 150,
        dialogBackgroundColor: "#252526",
        dialogTextColor: "#cccccc",
        dialogBorderColor: "#3c3c3c",
        dialogCloseButtonTextColor: "#cccccc",
        dialogCloseButtonBackgroundColor: "#2d2d2d",
        dialogSetButtonTextColor: "#ffffff",
        dialogSetButtonBackgroundColor: "#0e639c",
        dialogSetButtonBorderColor: "#007acc",
      };
    default:
      return {
        id: id("obj"),
        type: "text",
        x: 0,
        y: 0,
        width: 160,
        height: 40,
        text: "Unknown",
        textStyle: { ...defaultTextStyle },
      };
  }
}
